workflows:
  android:
    name: build, test & publish Android version
    scripts: 
      - name: android ewhg
        script: |
          echo "Hello android build"
          echo "cool"
      
  ios:
    name: build, test & publish iOS version
    scripts: 
      - name: iOs jsjss
        script: |
         echo "Hell iOS build"  
         echo "dev"   